language: node_js
node_js:
  - "12.12.11"
before_script:
  - psql -c 'create database testdb;' -U postgres
  - cp local.config.travis.json local.config.json
install:
  - npm install
services:
  - postgresql 
after_success:
  - npm run coveralls
